"use client";

import { useEffect, useState } from "react";

type AssignmentType = "ANNOTATION" | "REVIEW";
type Member = { id: string; name: string; email: string; role: string };
type Assignment = { id: string; type: AssignmentType; userId: string; assignedAt: string; user: { name: string | null; email: string } };

export function AssetAssignmentPanel({ datasetId, assetId }: { datasetId: string; assetId: string }) {
  const [members, setMembers] = useState<Member[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]); const [selection, setSelection] = useState<Record<AssignmentType, string>>({ ANNOTATION: "", REVIEW: "" }); const [busy, setBusy] = useState<AssignmentType | null>(null); const [error, setError] = useState<string | null>(null);
  const base = `/api/datasets/${datasetId}/assets/${assetId}/assignments`;
  useEffect(() => { void Promise.all([fetch(`/api/datasets/${datasetId}/members`, { credentials: "same-origin" }), fetch(base, { credentials: "same-origin" })]).then(async ([membersResponse, assignmentsResponse]) => { if (membersResponse.ok) setMembers((await membersResponse.json() as { data: { items: Member[] } }).data.items); if (assignmentsResponse.ok) setAssignments((await assignmentsResponse.json() as { data: { assignments: Assignment[] } }).data.assignments); }); }, [base, datasetId]);
  const eligible = (type: AssignmentType) => members.filter((member) => type === "ANNOTATION" ? member.role === "LABELER" : member.role === "REVIEWER");
  async function apply(type: AssignmentType) { const userId = selection[type]; if (!userId) return; setBusy(type); setError(null); try { const response = await fetch(`${base}/${type}`, { method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId }) }); const payload = await response.json().catch(() => null) as { data?: { assignmentId: string }; error?: { message?: string } } | null; const assignmentId = payload?.data?.assignmentId; if (!response.ok || !assignmentId) { setError(payload?.error?.message ?? "The assignment could not be saved."); return; } const member = eligible(type).find((item) => item.id === userId); setAssignments((items) => [...items.filter((item) => item.type !== type), { id: assignmentId, type, userId, assignedAt: new Date().toISOString(), user: { name: member?.name ?? null, email: member?.email ?? "" } }]); } finally { setBusy(null); } }
  async function clear(type: AssignmentType) { setBusy(type); setError(null); try { const response = await fetch(`${base}/${type}`, { method: "DELETE", credentials: "same-origin" }); if (!response.ok) { const payload = await response.json().catch(() => null) as { error?: { message?: string } } | null; setError(payload?.error?.message ?? "The assignment could not be removed."); return; } setAssignments((items) => items.filter((item) => item.type !== type)); } finally { setBusy(null); } }
  return <section className="mt-5 border-t border-zinc-100 pt-5"><h3 className="text-sm font-bold text-zinc-950">Responsibilities</h3><p className="mt-1 text-xs text-zinc-500">Assignments are separate from annotation and review workflow status.</p><div className="mt-3 grid gap-3">{(["ANNOTATION", "REVIEW"] as const).map((type) => { const assigned = assignments.find((item) => item.type === type) ?? null; return <div key={type} className="rounded-xl border border-zinc-200 p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold text-zinc-800">{type === "ANNOTATION" ? "Annotation" : "Review"}</span><span className="text-xs text-zinc-500">{assigned ? assigned.user.name ?? assigned.user.email : "Unassigned"}</span></div><div className="mt-2 flex gap-2"><select value={selection[type]} onChange={(event) => setSelection((current) => ({ ...current, [type]: event.target.value }))} disabled={busy !== null} className="min-w-0 flex-1 rounded-lg border border-zinc-200 bg-white px-2 py-1.5 text-xs"><option value="">Choose eligible member</option>{eligible(type).map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select><button type="button" disabled={!selection[type] || busy !== null} onClick={() => void apply(type)} className="rounded-lg bg-zinc-900 px-2 py-1.5 text-xs font-semibold text-white disabled:opacity-50">Assign</button>{assigned ? <button type="button" disabled={busy !== null} onClick={() => void clear(type)} className="rounded-lg border border-zinc-200 px-2 py-1.5 text-xs font-semibold text-zinc-700">Unassign</button> : null}</div></div>; })}</div>{error ? <p role="alert" className="mt-2 text-xs text-rose-700">{error}</p> : null}</section>;
}
