import "../../../../scripts/db-safety/test-entry.cjs"; // G1: verify disposable target before fixtures.
import assert from "node:assert/strict";
import { spawn, type ChildProcess } from "node:child_process";
import { randomBytes } from "node:crypto";
import test, { after, before } from "node:test";
import { DatasetMemberRole, UserRole } from "@internal/db";
import { hashPassword } from "@/lib/auth";
import { db } from "@/lib/db";
import { hasIntegrationDatabase } from "../auth-ownership/helpers";

const enabled = process.env.WORKSPACE_INTEGRATION_TESTS === "1" && hasIntegrationDatabase; const port = 3125; const base = `http://127.0.0.1:${port}`; const password = "assignment-http-password"; const marker = `${Date.now()}-${randomBytes(4).toString("hex")}`;
let server: ChildProcess | undefined; const ids = { owner: "", labeler: "", reviewer: "", outsider: "", dataset: "", asset: "" }; const cookies = { owner: "", outsider: "" };
function session(response: Response) { const token = /^fieldframe_session=([^;]+)/.exec(response.headers.get("set-cookie") ?? "")?.[1]; assert.ok(token); return `fieldframe_session=${token}`; }
async function wait() { for (let index = 0; index < 60; index += 1) { try { if ((await fetch(`${base}/api/auth/me`)).status < 500) return; } catch { /* start */ } await new Promise((resolve) => setTimeout(resolve, 250)); } throw new Error("Assignment HTTP server did not start."); }
async function login(email: string) { const response = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); if (response.status !== 200) throw new Error(`Login failed (${response.status}): ${await response.text()}`); return session(response); }
before(async () => { if (!enabled) return; const passwordHash = await hashPassword(password); const users = await Promise.all(["owner", "labeler", "reviewer", "outsider"].map((name) => db.user.create({ data: { email: `${name}-assignment-${marker}@test.invalid`, passwordHash, role: name === "owner" ? UserRole.MANAGER : UserRole.LABELER }, select: { id: true, email: true } }))); [ids.owner, ids.labeler, ids.reviewer, ids.outsider] = users.map((user) => user.id); ids.dataset = (await db.dataset.create({ data: { ownerId: ids.owner, name: `assignment-${marker}` }, select: { id: true } })).id; await db.datasetMember.createMany({ data: [{ datasetId: ids.dataset, userId: ids.labeler, role: DatasetMemberRole.LABELER }, { datasetId: ids.dataset, userId: ids.reviewer, role: DatasetMemberRole.REVIEWER }] }); ids.asset = (await db.asset.create({ data: { datasetId: ids.dataset, modality: "IMAGE", filename: "assignment.png", mimeType: "image/png", sourceFingerprint: marker }, select: { id: true } })).id; server = spawn("node_modules/.bin/next", ["start", "--port", String(port)], { cwd: process.cwd(), env: { ...process.env }, stdio: "ignore" }); await wait(); cookies.owner = await login(users[0]!.email); cookies.outsider = await login(users[3]!.email); });
after(async () => { if (server?.exitCode === null) await new Promise<void>((resolve) => { server?.once("exit", resolve); server?.kill("SIGTERM"); }); if (ids.dataset) await db.dataset.deleteMany({ where: { id: ids.dataset } }); await db.user.deleteMany({ where: { id: { in: [ids.owner, ids.labeler, ids.reviewer, ids.outsider].filter(Boolean) } } }); });
test("typed assignment HTTP commands authorize, conceal scope, and expose current/history reads", { skip: !enabled }, async () => { const path = `/api/datasets/${ids.dataset}/assets/${ids.asset}/assignments`; const hidden = await fetch(`${base}${path}/ANNOTATION`, { method: "PUT", headers: { "content-type": "application/json", Cookie: cookies.outsider }, body: JSON.stringify({ userId: ids.labeler }) }); assert.equal(hidden.status, 404); const assigned = await fetch(`${base}${path}/ANNOTATION`, { method: "PUT", headers: { "content-type": "application/json", Cookie: cookies.owner }, body: JSON.stringify({ userId: ids.labeler }) }); assert.equal(assigned.status, 201); const invalid = await fetch(`${base}${path}/REVIEW`, { method: "PUT", headers: { "content-type": "application/json", Cookie: cookies.owner }, body: JSON.stringify({ userId: ids.labeler }) }); assert.equal(invalid.status, 409); const read = await fetch(`${base}${path}`, { headers: { Cookie: cookies.owner } }); assert.equal(read.status, 200); const body = await read.json() as { data: { assignments: unknown[]; history: unknown[] } }; assert.equal(body.data.assignments.length, 1); assert.equal(body.data.history.length, 1); });
