import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import test, { after, before } from "node:test";
import { spawn, type ChildProcess } from "node:child_process";
import { resolve } from "node:path";
import { UserRole } from "@internal/db";
import { hashPassword } from "@/lib/auth";
import { db } from "@/lib/db";
import { buildSafeManifest, configureLocalImportHostMinio, hasImportIntegration, noSensitiveImportFields } from "./helpers";

const port = 3111; const baseUrl = `http://127.0.0.1:${port}`; const password = "phase010-start-password"; const suffix = randomBytes(5).toString("hex");
let server: ChildProcess | undefined; let managerCookie = ""; let labelerCookie = ""; let ids: string[] = [];
async function login(email: string) { const response = await fetch(`${baseUrl}/api/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); assert.equal(response.status, 200); return `fieldframe_session=${/^fieldframe_session=([^;]+)/.exec(response.headers.get("set-cookie") ?? "")?.[1]}`; }
before(async () => { if (!hasImportIntegration) return; configureLocalImportHostMinio(); const passwordHash = await hashPassword(password); const users = await Promise.all([db.user.create({ data: { email: `start-manager-${suffix}@phase010.test`, passwordHash, role: UserRole.MANAGER } }), db.user.create({ data: { email: `start-labeler-${suffix}@phase010.test`, passwordHash, role: UserRole.LABELER } })]); ids = users.map((u) => u.id); server = spawn("node_modules/.bin/next", ["start", "--port", String(port)], { cwd: process.cwd(), env: { ...process.env, MINIO_ENDPOINT: "http://localhost:9000", MINIO_PUBLIC_ENDPOINT: "http://localhost:9000", PRISMA_QUERY_ENGINE_LIBRARY: resolve(process.cwd(), "../../lib/generated/prisma/libquery_engine-debian-openssl-3.0.x.so.node") }, stdio: "ignore" }); for(let i=0;i<60;i+=1){try{if((await fetch(`${baseUrl}/api/auth/me`)).status===401)break;}catch{} await new Promise(r=>setTimeout(r,250));} managerCookie=await login(users[0]!.email); labelerCookie=await login(users[1]!.email); });
after(async()=>{if(server?.exitCode===null){server.kill("SIGTERM");} if(ids.length){await db.dataset.deleteMany({where:{ownerId:{in:ids}}});await db.user.deleteMany({where:{id:{in:ids}}});}});
test("authorized manager starts a mixed import through HTTP with safe response", {skip:!hasImportIntegration}, async()=>{const manifest=buildSafeManifest([{logicalPath:"x/a.png",contentType:"image/png",body:"a"},{logicalPath:"x/a.mp4",contentType:"video/mp4",body:"b"},{logicalPath:"x/a.txt",contentType:"text/plain",body:"c"},{logicalPath:"x/a.wav",contentType:"audio/wav",body:"d"}]); const response=await fetch(`${baseUrl}/api/imports/local-folder`,{method:"POST",headers:{"Content-Type":"application/json",Cookie:managerCookie},body:JSON.stringify({name:"mixed",idempotencyKey:randomBytes(20).toString("hex"),items:manifest})});assert.ok([201,202].includes(response.status));const body=await response.json();assert.ok(noSensitiveImportFields(body));const p=body.data.preparation;assert.equal((await db.preparedImportItem.count({where:{preparedImportId:p.id}})),4);assert.equal((await db.job.findUniqueOrThrow({where:{id:p.jobId}})).type,"IMPORT_DATASET");});
test("invalid or denied start has no durable side effect", {skip:!hasImportIntegration}, async()=>{const before=await db.preparedImport.count();const denied=await fetch(`${baseUrl}/api/imports/local-folder`,{method:"POST",headers:{"Content-Type":"application/json",Cookie:labelerCookie},body:JSON.stringify({name:"x",idempotencyKey:randomBytes(20).toString("hex"),items:buildSafeManifest()})});assert.equal(denied.status,403);assert.equal(await db.preparedImport.count(),before);});

test("authorized workspace append creates another preparation for the same Dataset and replays its idempotency key", {skip:!hasImportIntegration}, async()=>{const created=await fetch(`${baseUrl}/api/imports/local-folder`,{method:"POST",headers:{"Content-Type":"application/json",Cookie:managerCookie},body:JSON.stringify({name:"append-target",idempotencyKey:randomBytes(20).toString("hex"),items:buildSafeManifest()})});assert.ok([201,202].includes(created.status));const datasetId=(await created.json()).data.preparation.datasetId;const key=randomBytes(20).toString("hex");const body={idempotencyKey:key,items:buildSafeManifest([{logicalPath:"append/second.txt"}])};const first=await fetch(`${baseUrl}/api/datasets/${datasetId}/imports/local-folder`,{method:"POST",headers:{"Content-Type":"application/json",Cookie:managerCookie},body:JSON.stringify(body)});assert.ok([201,202].includes(first.status));const firstData=(await first.json()).data.preparation;assert.equal(firstData.datasetId,datasetId);const replay=await fetch(`${baseUrl}/api/datasets/${datasetId}/imports/local-folder`,{method:"POST",headers:{"Content-Type":"application/json",Cookie:managerCookie},body:JSON.stringify(body)});assert.equal(replay.status,200);assert.equal((await replay.json()).data.preparation.id,firstData.id);assert.equal(await db.preparedImport.count({where:{datasetId}}),2);});

test("absolute paths and binary-shaped JSON are rejected without durable records", {skip:!hasImportIntegration}, async()=>{const before=await Promise.all([db.dataset.count(),db.job.count(),db.preparedImport.count(),db.asset.count()]);for(const item of [{logicalPath:"/home/user/a.jpg",contentType:"image/png",sizeBytes:1,fingerprint:"a".repeat(64)},{logicalPath:"folder/a.jpg",contentType:"image/png",sizeBytes:1,fingerprint:"b".repeat(64),binary:"not-allowed"}]){const response=await fetch(`${baseUrl}/api/imports/local-folder`,{method:"POST",headers:{"Content-Type":"application/json",Cookie:managerCookie},body:JSON.stringify({name:"invalid",idempotencyKey:randomBytes(20).toString("hex"),items:[item]})});assert.equal(response.status,400);const body=await response.json();assert.equal(body.error.code,"INVALID_REQUEST");assert.equal(noSensitiveImportFields(body),true);}assert.deepEqual(await Promise.all([db.dataset.count(),db.job.count(),db.preparedImport.count(),db.asset.count()]),before);});
