import "../../../../scripts/db-safety/test-entry.cjs"; // G1: verify disposable target before fixtures.
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { db } from "@/lib/db";
import { authorizeFoundationJobSubmission } from "@/lib/jobs/authorization";
import { requestVisualizationProcessing } from "@/lib/visualization/processing-service";
import { readVersions, readSnapshotContent, readPublishedProfile, currentPreview, artifactBytes } from "@/lib/visualization/snapshot-read";
import { readVisualizationMedia } from "@/lib/visualization/media-read";
import { getWebProviders } from "@/lib/providers";
import { processVisualization } from "../../../worker/src/jobs/visualization.processor";
import { claimJob } from "../../../worker/src/jobs/job-claim-lock";
import { defaultReferenceCheckers } from "../../../worker/src/queue/minio-orphan-scanner";
import { captureDatasetAssetStorageKeys } from "../../../worker/src/queue/deleted-dataset-cleanup";
import { routeQueueDelivery } from "../../../worker/src/queue/queue-router";

// Real PostgreSQL, MinIO and ffmpeg. The transport stub isolates these Jobs from live queues.
test("immutable capture, duplicate delivery, failed derivation, successor retry, generation invalidation and frozen media", async () => {
  const user = await db.user.create({ data: { email: `vis4-process-${randomUUID()}@test.invalid`, name: "Processor test", role: "MANAGER" } });
  const actor = { ...user, name: user.name! };
  const dataset = await db.dataset.create({ data: { ownerId: user.id, name: "Processing test", metadata: { workflowStatus: "COMPLETED" } } });
  const { minio } = getWebProviders(); const bucket = process.env.MINIO_BUCKET!;
  const sourceKey = `vis4-test/${dataset.id}/source.png`;
  const source = await readFile(new URL("../fixtures/visualization.png", import.meta.url));
  const deliveries: unknown[] = [];
  const options = { createQueue: () => ({ queue: { add: async (_name: string, payload: unknown) => { deliveries.push(payload); } }, close: async () => {} }) };
  const run = async (id: string, hooks: Parameters<typeof processVisualization>[3] = {}) => { const claim = await claimJob(db, { jobId: id, workerId: "visualization-test" }); if (claim.kind !== "claimed") throw new Error("claim failed"); return processVisualization(db, id, claim.lockToken, hooks); };
  try {
    await minio.putObject(bucket, sourceKey, source, source.length, { "Content-Type": "image/png" });
    const asset = await db.asset.create({ data: { datasetId: dataset.id, filename: "source.png", modality: "IMAGE", mimeType: "image/png", width: 200, height: 100, sourceFingerprint: randomUUID(), storageProvider: "MINIO", storageBucket: bucket, storageKey: sourceKey, sizeBytes: BigInt(source.length) } });
    const label = await db.label.create({ data: { datasetId: dataset.id, name: "Object", normalizedName: "object", color: "#abcdef" } });
    const annotation = await db.annotation.create({ data: { datasetId: dataset.id, assetId: asset.id, createdById: user.id, labelId: label.id, modality: "IMAGE", type: "BOUNDING_BOX", geometry: { x: 0.1, y: 0.1, width: 0.2, height: 0.3 } } });
    assert.equal((await requestVisualizationProcessing({ ...actor, id: "outsider" }, dataset.id, undefined, options)).ok, false);
    assert.equal((await authorizeFoundationJobSubmission(actor, { datasetId: dataset.id, type: "VISUALIZATION_CAPTURE", input: { generation: "0" } })).ok, false);
    assert.equal((await readVersions(dataset.id, 1, 20)).total, 0);
    const request = await requestVisualizationProcessing(actor, dataset.id, undefined, options); assert.ok(request.ok);
    const duplicate = await requestVisualizationProcessing(actor, dataset.id, undefined, options); assert.ok(duplicate.ok); assert.equal(duplicate.job.id, request.job.id);
    assert.deepEqual(deliveries, [{ jobId: request.job.id }]);
    assert.equal(await run(request.job.id), "completed");
    assert.equal((await routeQueueDelivery({ db, payload: { jobId: request.job.id } })).kind, "skipped");
    const first = (await readVersions(dataset.id, 1, 20)).items[0]; assert.equal(first.ordinal, 1);
    const frozen = await readSnapshotContent(dataset.id, first.id, 1, 20);
    assert.equal(frozen.annotations[0].revision, 1); assert.equal(frozen.labels[0].color, "#abcdef");
    const copied = await db.visualizationArtifact.findFirstOrThrow({ where: { snapshotId: first.id, kind: "SOURCE_IMAGE" } });
    assert.deepEqual(await artifactBytes(copied), source);
    const derive = await db.job.findFirstOrThrow({ where: { datasetId: dataset.id, type: "VISUALIZATION_DERIVE" } });
    assert.equal((await readVisualizationMedia(dataset.id, asset.id)).headers.get("X-Visualization-Preview"), null);
    assert.equal(await run(derive.id, { render: async () => { throw new Error("renderer failed"); } }), "failed");
    assert.equal((await readVisualizationMedia(dataset.id, asset.id)).status, 200);
    const retry = await requestVisualizationProcessing(actor, dataset.id, derive.id, options); assert.ok(retry.ok);
    const retryAgain = await requestVisualizationProcessing(actor, dataset.id, derive.id, options); assert.ok(retryAgain.ok); assert.equal(retryAgain.job.id, retry.job.id);
    assert.equal(await run(retry.job.id), "completed");
    assert.equal((await readPublishedProfile(dataset.id)).profile?.annotationCount, 1);
    assert.equal((await readVisualizationMedia(dataset.id, asset.id)).headers.get("X-Visualization-Preview"), "ready");
    const ready = await currentPreview(dataset.id, asset.id, "THUMBNAIL"); assert.ok(ready);
    await assert.rejects(db.visualizationArtifact.update({ where: { id: ready.id }, data: { sha256: "bad" } }));
    const repeat = await db.job.create({ data: { datasetId: dataset.id, createdById: user.id, type: "VISUALIZATION_DERIVE", input: derive.input! } });
    assert.equal(await run(repeat.id, { render: async () => { throw new Error("regeneration failed"); } }), "failed");
    assert.equal((await currentPreview(dataset.id, asset.id, "THUMBNAIL"))?.id, ready.id);
    await assert.rejects(db.visualizationArtifact.delete({ where: { id: ready.id } }));
    const count = await db.visualizationArtifact.count({ where: { datasetId: dataset.id } });
    const repeatSuccess = await requestVisualizationProcessing(actor, dataset.id, repeat.id, options); assert.ok(repeatSuccess.ok); assert.equal(await run(repeatSuccess.job.id), "completed");
    assert.equal(await db.visualizationArtifact.count({ where: { datasetId: dataset.id } }), count);
    await db.annotation.update({ where: { id: annotation.id }, data: { revision: { increment: 1 }, geometry: { x: 0.2, y: 0.2, width: 0.3, height: 0.4 } } });
    assert.equal(await currentPreview(dataset.id, asset.id, "THUMBNAIL"), null);
    assert.deepEqual(await readSnapshotContent(dataset.id, first.id, 1, 20), frozen);
    const pending = await requestVisualizationProcessing(actor, dataset.id, undefined, options); assert.ok(pending.ok);
    assert.equal(await run(pending.job.id, { beforePublish: async () => { await db.label.update({ where: { id: label.id }, data: { color: "#123456" } }); } }), "failed");
    assert.equal((await readVersions(dataset.id, 1, 20)).total, 1);
    const successor = await requestVisualizationProcessing(actor, dataset.id, pending.job.id, options); assert.ok(successor.ok); assert.equal(await run(successor.job.id), "completed");
    assert.equal((await readVersions(dataset.id, 1, 20)).total, 2);
    const retainedProfile = await readPublishedProfile(dataset.id);
    assert.equal(retainedProfile.profileSnapshotId, first.id);
    assert.equal(retainedProfile.profileCurrent, false);
    assert.equal(retainedProfile.profile?.annotationCount, 1);
    await minio.removeObject(bucket, sourceKey);
    assert.deepEqual(await artifactBytes(copied), source);
    assert.deepEqual(await readSnapshotContent(dataset.id, first.id, 1, 20), frozen);
    const reference = { db, bucket: copied.bucket, key: copied.key };
    assert.equal(await defaultReferenceCheckers[0](reference), true);
    assert.ok((await captureDatasetAssetStorageKeys(db, dataset.id)).some(r => r.key === copied.key));
    await db.dataset.update({ where: { id: dataset.id }, data: { archivedAt: new Date() } });
    assert.equal(await defaultReferenceCheckers[0](reference), true, "archived snapshots are retained");
    await db.dataset.update({ where: { id: dataset.id }, data: { deletedAt: new Date() } });
    assert.equal(await defaultReferenceCheckers[0](reference), false, "deleted dataset artifacts become eligible for existing delayed cleanup");
  } finally {
    const names: string[] = [sourceKey];
    for await (const entry of minio.listObjectsV2(bucket, `visualization/${dataset.id}/`, true)) if (entry.name) names.push(entry.name);
    await db.dataset.delete({ where: { id: dataset.id } }); await db.user.delete({ where: { id: user.id } });
    await minio.removeObjects(bucket, names);
  }
});
