export const VIDEO_ANNOTATION_ERRORS = {
  TRACK_REVISION_CONFLICT: "VIDEO_TRACK_REVISION_CONFLICT",
  ANNOTATION_REVISION_CONFLICT: "ANNOTATION_REVISION_CONFLICT",
  UNSUPPORTED_VIDEO_MODIFICATION: "UNSUPPORTED_VIDEO_MODIFICATION",
  DUPLICATE_KEYFRAME_TIMESTAMP: "VIDEO_KEYFRAME_TIMESTAMP_CONFLICT",
  INVALID_VIDEO_GEOMETRY: "INVALID_VIDEO_GEOMETRY",
  INVALID_VIDEO_TIME_RANGE: "INVALID_VIDEO_TIME_RANGE",
  VIDEO_ANNOTATION_LIMIT_EXCEEDED: "VIDEO_ANNOTATION_LIMIT_EXCEEDED",
} as const;

export type VideoAnnotationErrorCode = typeof VIDEO_ANNOTATION_ERRORS[keyof typeof VIDEO_ANNOTATION_ERRORS];
