import { NextResponse } from "next/server";

export type ApiErrorCode =
  | "DATASET_MODALITY_UNRESOLVED"
  | "DATASET_MODALITY_IMMUTABLE"
  | "DATASET_MODALITY_CONFLICT"
  | "DATASET_NOT_EMPTY"
  | "ASSET_MODALITY_MISMATCH"
  | "AUTH_REQUIRED"
  | "FORBIDDEN"
  | "INVALID_REQUEST"
  | "GITEA_CONFIGURATION_ERROR"
  | "GITEA_UNAVAILABLE"
  | "GITEA_NOT_FOUND"
  | "GITEA_RATE_LIMITED"
  | "GITEA_RESPONSE_INVALID"
  | "UPLOAD_CONFLICT"
  | "UPLOAD_NOT_READY"
  | "INVALID_RELATIVE_PATH"
  | "ASSET_WRITES_PAUSED_FOR_MIGRATION"
  | "UNSUPPORTED_MEDIA"
  | "INVALID_MEDIA"
  | "ASSET_UNAVAILABLE"
  | "DATASET_NOT_COMPLETED"
  | "DATASET_NOT_FOUND"
  | "JOB_NOT_FOUND"
  | "JOB_CONFLICT"
  | "IMPORT_INCOMPLETE"
  | "IMPORT_COMMIT_TIMEOUT"
  | "IMPORT_PREPARATION_CONFLICT"
  | "IDEMPOTENCY_KEY_CONFLICT"
  | "SOURCE_URL_UNSAFE"
  | "SOURCE_DESTINATION_NOT_ALLOWED"
  | "SOURCE_ROOT_PATH_UNSAFE"
  | "SOURCE_IMPORT_LIMIT_EXCEEDED"
  | "SOURCE_CONNECTION_UNSUPPORTED"
  | "SOURCE_CONNECTION_EXISTS"
  | "SOURCE_TOKEN_EXPIRED"
  | "SOURCE_TOKEN_INVALID"
  | "SOURCE_PROVIDER_UNAVAILABLE"
  | "SOURCE_CONNECTION_IN_USE"
  | "SOURCE_CONNECTION_NOT_FOUND"
  | "UNSUPPORTED_PROVIDER"
  | "UNSAFE_REPOSITORY_URL"
  | "REPOSITORY_NOT_FOUND"
  | "REPOSITORY_ACCESS_DENIED"
  | "REF_NOT_FOUND"
  | "ROOT_PATH_NOT_FOUND"
  | "ONE_TIME_PAT_REQUIRES_SAVE_FOR_ASYNC_IMPORT"
  | "GITEA_IMPORT_DEPRECATED"
  | "SOURCE_IMPORT_JOBS_DEPRECATED"
  | "IMAGE_CONTENT_DEPRECATED"
  | "ANNOTATION_REVISION_CONFLICT"
  | "ANNOTATION_WRITE_UNSUPPORTED_FOR_MODALITY"
  | "ANNOTATION_CREATE_REPLAY_CONFLICT"
  | "VIDEO_TRACK_REVISION_CONFLICT"
  | "VIDEO_KEYFRAME_TIMESTAMP_CONFLICT"
  | "ANNOTATION_NOT_FOUND"
  | "MEDIA_REQUEST_INVALID"
  | "MEDIA_ASSET_NOT_FOUND"
  | "MEDIA_ASSET_INELIGIBLE"
  | "MEDIA_SOURCE_MISSING"
  | "MEDIA_SOURCE_STALE"
  | "MEDIA_PROCESSOR_UNAVAILABLE"
  | "MEDIA_ENQUEUE_REFUSED"
  | "AI_MODEL_LABELS_UNAVAILABLE"
  | "AI_MODEL_CATALOG_UNAVAILABLE"
  | "AI_MODEL_INACTIVE"
  | "AI_MODEL_NOT_FOUND"
  | "ASSET_NOT_IN_DATASET"
  | "TARGET_EMPTY"
  | "TARGET_TOO_LARGE"
  | "TARGET_MIXED_MODALITY"
  | "TARGET_INELIGIBLE"
  | "TARGET_CHANGED"
  | "AI_CAPABILITY_UNVERIFIED"
  | "AI_TASK_NOT_FOUND"
  | "RATE_LIMITED"
  | "INTERNAL_ERROR"
  | "SELECTION_TOO_LARGE"
  | "ANNOTATION_REFERENCE_WARNING"
  | "INVALID_ASSIGNEE"
  | "LABEL_NOT_FOUND"
  | "BULK_ACTION_NOT_IMPLEMENTED"
  | "STALE_REVISION"
  | "INVALID_TRANSITION"
  | "WORKFLOW_STATUS_REQUIRES_TRANSITION"
  | "INVITATION_NOT_FOUND"
  | "INVITATION_CONFLICT"
  | "COLLABORATION_MEMBER_NOT_FOUND"
  | "COLLABORATION_ASSIGNMENT_NOT_FOUND"
  | "COLLABORATION_COMMENT_NOT_FOUND"
  | "COLLABORATION_COMMENT_DEPTH_INVALID"
  | "COLLABORATION_NOTIFICATION_NOT_FOUND"
  | "REALTIME_TICKET_INVALID";

export function apiError(
  status: number,
  code: ApiErrorCode,
  message: string,
  fieldErrors?: Record<string, string[]>,
  headers?: Record<string, string>,
  extra?: Record<string, unknown>,
) {
  return NextResponse.json(
    {
      error: {
        code,
        message,
        ...(fieldErrors ? { fieldErrors } : {}),
        ...(extra ?? {}),
      },
    },
    {
      status,
      headers: {
        "Cache-Control": "no-store",
        "X-Content-Type-Options": "nosniff",
        ...headers,
      },
    },
  );
}

export function apiSuccess<T>(data: T, init?: ResponseInit) {
  const headers = new Headers(init?.headers);
  headers.set("Cache-Control", "no-store");
  headers.set("X-Content-Type-Options", "nosniff");

  return NextResponse.json(
    { data },
    {
      ...init,
      headers,
    },
  );
}
